import { Button, Modal, Layout } from 'antd'
import Head from 'next/head'
import styles from '../styles/Home.module.less'
import React, { useState } from 'react'
import Image from 'next/image';
import LogoImage from '../components/LogoImage';
import ListContent from '../components/ListContent';

const { Header, Content, Footer } = Layout;

export default function Home(props) {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const showModal = () => {
    setIsModalOpen(true);
  };

  const handleOk = () => {
    setIsModalOpen(false);
  };

  const handleCancel = () => {
    setIsModalOpen(false);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(props.results)}
      {/* Header */}
      <Header className={styles.header}>
        <LogoImage />
        {/* Navbar with search */}
      </Header>

      {/* Results */}
      <Content className={[styles.container, styles.content]}>
        <ListContent results={props.results} />
      </Content>
    </div>
  )
}

export const getServerSideProps = async (context) => {

  const offset = context?.query.offset ? context?.query.offset : 0;

  const results = await fetch(`https://kitsu.io/api/edge/anime?page[limit]=10&page[offset]=${offset}`)
    .then(res => res.json())

    console.log(context.query)

  return {
    props: {
      results
    }
  }
}